version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - sudo apt-get install zip gzip tar -y
      - pip3 install --upgrade pip
      - pip install taskcat==0.8.49    
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - cp ec2/*.json templates/
      - export dirname=${PWD##*/}
      - echo Directory name $dirname
      - cd ..
      - mv $dirname $PROJECTNAME
  build:
    commands:
      - echo Entered the build phase...
      - taskcat -c $PROJECTNAME/ci/taskcat.yml
  post_build:
    commands:
      - echo uploading report to $ARTIFACT_BUCKET S3 bucket
      - |
        if [ -d "taskcat_outputs" ]
        then
          aws s3 sync taskcat_outputs s3://$ARTIFACT_BUCKET/taskcat_reports/$CODEBUILD_BUILD_ID
        else
          echo Validation FAILED!
          exit 1
        fi
      - |
        if $(grep -Fq "CREATE_FAILED" taskcat_outputs/index.html)
        then
          echo Validation FAILED!
          exit 1
        else
          echo Validation Passed!
          exit 0
        fi
